#! /bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".ts$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating Javascript:\n"

# Check for tslint
which tslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install tslint (yarn global add tslint)\033[0m"
  exit 1
fi

npm run tslintcheck
if [[ "$?" != 0 ]]; then
  PASS=false
fi

echo "\TSLINT Validation Complete\n"

if ! $PASS; then
    echo "\033[31mCOMMIT FAILED:\033[0m Your commit contains files that failed ESLint.\n"
    echo "Please fix the tslint errors and try to commit again."
exit 1
fi

exit $?
